name: UPX Action
description: GitHub Action to run UPX on an executable
author: tarampampam

branding:
  icon: file-minus
  color: blue

inputs:
  infile:
    description: 'Input file(s)'
    required: true
  upx_args:
    description: 'Arguments to pass to UPX'

runs:
  using: docker
  image: Dockerfile
