name: Test

on: [push, pull_request]

jobs:
  test:
    name: Test action on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-latest]
    steps:
      - name: Compile test file
        run: |
          printf %s 'package main;import "fmt";func main(){fmt.Println("hi")}' > main.go
          go build -o hi main.go

      - name: Run current action
        uses: tarampampam/upx-action@${{ github.ref }}
        with:
          infile: 'hi'
          upx_args: '-9'

      - name: Rest results
        run: test "$(./hi)" == hi
