# https://help.github.com/en/articles/contexts-and-expression-syntax-for-github-actions
name: Test action

on: [push]

jobs:
  test-file:
    name: Test action on ${{ matrix.os }} using file
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, ubuntu-latest]
    steps:
      - name: Check out code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Compile test file
        run: |
          printf %s 'package main;import "fmt";func main(){fmt.Println("hi")}' > main.go
          go build -o ./hi main.go
          md5sum ./hi | cut -c -32 > hi.md5

      - name: Run current action (pack file)
        uses: ./
        with:
          file: './hi'
          upx_args: '-7'

      - name: Test packed file execution
        run: test "$(./hi)" = hi

      - name: Test packed file checksum
        run: test $(cat ./hi.md5) != $(md5sum ./hi | cut -c -32)

      - name: Unpack file
        uses: tarampampam/upx-action@master
        with:
          file: './hi'
          upx_args: '-d'

      - name: Test unpacked file execution
        run: test "$(./hi)" = hi

      - name: Test unpacked file checksum
        run: test $(cat ./hi.md5) = $(md5sum ./hi | cut -c -32)

  test2:
    name: Test action on ${{ matrix.os }} using directory
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, ubuntu-latest]
    steps:
      - name: Check out code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Compile test files
        run: |
          printf %s 'package main;import "fmt";func main(){fmt.Println("hi1")}' > main1.go
          printf %s 'package main;import "fmt";func main(){fmt.Println("hi2")}' > main2.go
          go build -o hi1 main1.go
          go build -o hi2 main2.go
          md5sum ./hi1 | cut -c -32 > hi1.md5
          md5sum ./hi2 | cut -c -32 > hi2.md5

      - name: Run current action (pack files in directory)
        uses: ./
        with:
          dir: '.'
          upx_args: '-7'

      - name: Test packed files execution
        run: |
          test "$(./hi1)" = hi1
          test "$(./hi2)" = hi2

      - name: Test packed files checksums
        run: |
          test $(cat ./hi1.md5) != $(md5sum ./hi1 | cut -c -32)
          test $(cat ./hi2.md5) != $(md5sum ./hi2 | cut -c -32)

      - name: Unpack files
        uses: tarampampam/upx-action@master
        with:
          dir: '.'
          upx_args: '-d'

      - name: Test unpacked files execution
        run: |
          test "$(./hi1)" = hi1
          test "$(./hi2)" = hi2

      - name: Test unpacked files checksums
        run: |
          test $(cat ./hi1.md5) = $(md5sum ./hi1 | cut -c -32)
          test $(cat ./hi2.md5) = $(md5sum ./hi2 | cut -c -32)
