# https://help.github.com/en/articles/contexts-and-expression-syntax-for-github-actions
name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test action on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-latest]
    steps:
      - name: Compile test file
        run: |
          printf %s 'package main;import "fmt";func main(){fmt.Println("hi")}' > main.go
          go build -o hi main.go
          mkdir ./dir
          cp ./hi ./dir/hi1
          cp ./hi ./dir/hi2

      - name: Run current action (for file)
        uses: tarampampam/upx-action@master
        with:
          infile: 'hi'
          upx_args: '-9'

      - name: Test results (for file)
        run: test "$(./hi)" == hi

      - name: Run current action (for directory)
        uses: tarampampam/upx-action@master
        with:
          indir: ./dir
          upx_args: '-9'

      - name: Test results (for directory, first file)
        run: test "$(./dir/hi1)" == hi

      - name: Test results (for directory, seconf file)
        run: test "$(./dir/hi2)" == hi
